'use strict';
const fs = require('node:fs');
const path = require('node:path');
const root = path.resolve(__dirname, '..');
const read = name => fs.readFileSync(path.join(root, 'dist', name), 'utf8');
const scripts = ['catalog.js', 'units.js', 'rearrange.js', 'fill-height.js', 'custom-formula.js', 'engine.js', 'geometry.js', 'solid-preview.js', 'tour.js', 'app.js'];
let html = read('index.html');
const css = read('styles.css');
if (/<\/style/i.test(css)) throw new Error('Stylesheet contains a closing style tag.');
html = html.replace('<link rel="stylesheet" href="styles.css">', () => '<style>\n' + css + '\n</style>');
for (const file of scripts) html = html.replace(`<script src="${file}" defer></script>`, '');
const inline = scripts.map(file => {
  const source = read(file);
  if (/<\/script/i.test(source)) throw new Error(file + ' contains a closing script tag.');
  return `<script>\n/* ${file} */\n${source}\n</script>`;
}).join('\n');
// Inline scripts run after the markup. Source scripts use defer in dist/index.html.
html = html.replace('</body>', () => inline + '\n</body>');
html = html.replace('<!doctype html>', '<!doctype html>\n<!-- Generated by tools/build.cjs. Edit the files in dist/ and rebuild. -->');
for (const [edition, filename] of [['standard','index.html'],['exam','eksamen.html']]) {
  let output = html;
  if (edition === 'exam') {
    output = output.replace('data-edition="standard"','data-edition="exam"')
      .replace('<title>P&P — Almindelig version</title>','<title>P&P — Eksamensversion</title>')
      .replace('<span data-edition-label>Almindelig · offline</span>','<span data-edition-label>Eksamen · offline</span>')
      .replace('value="Bassin med keglebund"','value="Ny opsætning"')
      .replace('>Gemmes på denne computer</span>','>Eksamensversion · gemmes ikke</span>')
      .replace('aria-pressed="false" aria-label="Lommeregner: fra"','aria-pressed="true" aria-label="Lommeregner: til"')
      .replace('<span class="toggle-state">Fra</span>','<span class="toggle-state">Til</span>');
    // Remove unavailable controls entirely, including the file picker.
    output = output.replace(/<(button|span)\b[^>]*\bdata-standard-only\b[^>]*>[\s\S]*?<\/\1>/g,'')
      .replace(/<input\b[^>]*\bdata-standard-only\b[^>]*>/g,'');
  }
  fs.writeFileSync(path.join(root, filename), output);
  console.log('Built '+filename+' ('+Buffer.byteLength(output)+' bytes). No external assets.');
}
