'use strict';
const fs = require('node:fs');
const path = require('node:path');
const root = path.resolve(__dirname, '..');
const read = name => fs.readFileSync(path.join(root, 'dist', name), 'utf8');
const scripts = ['catalog.js', 'units.js', 'engine.js', 'geometry.js', 'solid-preview.js', 'tour.js', 'app.js'];
let html = read('index.html');
const css = read('styles.css');
if (/<\/style/i.test(css)) throw new Error('Stylesheet contains a closing style tag.');
html = html.replace('<link rel="stylesheet" href="styles.css">', () => '<style>\n' + css + '\n</style>');
for (const file of scripts) html = html.replace(`<script src="${file}" defer></script>`, '');
const inline = scripts.map(file => {
  const source = read(file);
  if (/<\/script/i.test(source)) throw new Error(file + ' contains a closing script tag.');
  return `<script>\n/* ${file} */\n${source}\n</script>`;
}).join('\n');
// Inline scripts run after the markup. Source scripts use defer in dist/index.html.
html = html.replace('</body>', () => inline + '\n</body>');
html = html.replace('<!doctype html>', '<!doctype html>\n<!-- Generated by tools/build.cjs. Edit the files in dist/ and rebuild. -->');
fs.writeFileSync(path.join(root, 'index.html'), html);
console.log('Built standalone index.html (' + Buffer.byteLength(html) + ' bytes). No external assets.');
